'use client';

import { useState } from 'react';

function ActionBadge({ label }: { label: string }) {
  const colors: Record<string, string> = {
    PROPOSED: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
  };
  return (
    <span className={`text-2xs font-bold px-2 py-0.5 rounded border font-mono uppercase ${colors[label] ?? 'bg-slate-700/40 text-slate-400 border-slate-700/50'}`}>
      {label}
    </span>
  );
}

export default function ChangelogPanel({ changelog, releaseNotes, version }: {
  changelog: string;
  releaseNotes: string;
  version: string;
}) {
  const [tab, setTab] = useState<'changelog' | 'notes'>('changelog');

  return (
    <section>
      <div className="flex items-center justify-between mb-4">
        <div>
          <h2 className="text-lg font-semibold text-slate-100">Release Artifacts</h2>
          <p className="text-sm text-slate-400 mt-0.5">
            Version <span className="font-mono text-sky-400">{version}</span> — auto-generated by ReleasePilot AI
          </p>
        </div>
        <div className="flex gap-1 bg-slate-800/60 rounded-lg p-1 border border-slate-700/50">
          {(['changelog', 'notes'] as const).map(t => (
            <button
              key={t}
              onClick={() => setTab(t)}
              className={`px-3 py-1.5 text-xs font-semibold rounded-md transition-all ${
                tab === t
                  ? 'bg-blue-600 text-white'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {t === 'changelog' ? 'CHANGELOG.md' : 'Release Notes'}
            </button>
          ))}
        </div>
      </div>

      <div className="bg-slate-900/60 rounded-xl border border-slate-700/50 overflow-hidden">
        <div className="flex items-center gap-3 px-4 py-2.5 border-b border-slate-700/50 bg-slate-800/40">
          <div className="flex gap-1.5">
            <div className="w-3 h-3 rounded-full bg-red-500/70" />
            <div className="w-3 h-3 rounded-full bg-amber-500/70" />
            <div className="w-3 h-3 rounded-full bg-emerald-500/70" />
          </div>
          <span className="text-xs font-mono text-slate-400">
            {tab === 'changelog' ? 'CHANGELOG.md' : 'RELEASE_NOTES.md'}
          </span>
          <div className="ml-auto">
            <ActionBadge label="PROPOSED" />
          </div>
        </div>
        <pre className="p-5 text-xs font-mono text-slate-300 whitespace-pre-wrap leading-relaxed overflow-auto max-h-96">
          {tab === 'changelog' ? changelog : releaseNotes}
        </pre>
      </div>
    </section>
  );
}
